# Generated by Django 5.1.6 on 2025-02-13 09:36

import apps.manager
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('last_updated_at', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=10)),
                ('code', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyKorxona',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField()),
                ('last_updated_at', models.DateTimeField()),
                ('type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'company_korxona',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('jshshir', models.CharField(max_length=14, unique=True)),
                ('login', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('last_updated_at', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('avatar', models.CharField(blank=True, max_length=255)),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('education', models.CharField(blank=True, max_length=255)),
                ('nationality', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('birth_place', models.CharField(blank=True, max_length=255)),
                ('current_place', models.CharField(blank=True, max_length=255)),
                ('positions', models.TextField(default='[]')),
                ('roles', models.JSONField(default=list)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
            },
            managers=[
                ('objects', apps.manager.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CompanyKorxonaName',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('data', models.CharField(max_length=255)),
                ('lang', models.CharField(max_length=10)),
                ('company_korxona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_names', to='apps.companykorxona')),
            ],
            options={
                'db_table': 'company_korxona_name',
            },
        ),
        migrations.CreateModel(
            name='CompanyName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(blank=True, max_length=255)),
                ('lang', models.CharField(blank=True, max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='apps.company')),
            ],
        ),
    ]
